# Generated by Django 3.1.7 on 2021-04-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loaisp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('mota', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='San_pham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensp', models.CharField(default='', max_length=200)),
                ('phanloai', models.CharField(default='', max_length=200)),
                ('gia', models.IntegerField()),
                ('xuatxu', models.CharField(default='', max_length=50)),
                ('thuonghieu', models.CharField(default='', max_length=200)),
                ('soluong', models.IntegerField()),
                ('hdsd', models.TextField(default='')),
                ('mota', models.TextField(default='')),
                ('anhsp', models.ImageField(upload_to='product_pictures')),
                ('loaisp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.loaisp')),
            ],
        ),
    ]
