# Generated by Django 3.1.7 on 2021-04-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nhan_xet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binh_luan', models.TextField(default='')),
                ('diem', models.IntegerField(default=10)),
                ('thoi_gian', models.DateField()),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.khach_hang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.san_pham')),
            ],
        ),
    ]
