# Generated by Django 3.1.7 on 2021-04-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khach_hang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdt', models.CharField(max_length=15)),
                ('diachi', models.CharField(max_length=200)),
                ('tuoi', models.IntegerField(default=0)),
                ('gioi_tinh', models.CharField(max_length=15)),
            ],
        ),
    ]
