# Generated by Django 3.1.7 on 2021-05-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210421_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='khach_hang',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
