# Generated by Django 3.1.7 on 2021-05-02 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_auto_20210502_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khach_hang',
            name='user',
            field=models.OneToOneField(default=(), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
