# Generated by Django 3.1.7 on 2021-05-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210502_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khach_hang',
            name='user',
        ),
    ]
