# Generated by Django 3.1.7 on 2021-04-26 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0003_auto_20210421_2106'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don_dat_hang',
            name='khach_hang',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.khach_hang'),
        ),
        migrations.AlterField(
            model_name='don_dat_hang',
            name='ngay_dat',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='don_dat_hang',
            name='ngay_giao',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='don_dat_hang',
            name='san_pham',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.san_pham'),
        ),
        migrations.AlterField(
            model_name='don_dat_hang',
            name='so_luong',
            field=models.IntegerField(default=0),
        ),
    ]
