# Generated by Django 3.1.7 on 2021-04-26 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0003_auto_20210421_2106'),
        ('order', '0002_auto_20210426_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don_dat_hang',
            name='khach_hang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.khach_hang'),
        ),
        migrations.AlterField(
            model_name='don_dat_hang',
            name='san_pham',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.san_pham'),
        ),
    ]
